LRF_cfg.myTrellis_header.numInputSymbols = 2;
LRF_cfg.myTrellis_header.numOutputSymbols = 4;
LRF_cfg.myTrellis_header.numStates  = 16;
LRF_cfg.myTrellis_header.nextStates = [0  1  ; ...
                        2  3  ; ...
                        4  5  ; ...
                        6  7  ; ...
                        8  9  ; ...
                        10  11  ; ...
                        12  13  ; ...
                        14  15  ; ...
                        0  1  ; ...
                        2  3  ; ...
                        4  5  ; ...
                        6  7  ; ...
                        8  9  ; ...
                        10  11  ; ...
                        12  13  ; ...
                        14  15 ];
LRF_cfg.myTrellis_header.outputs    = [0  3  ; ...
                        1  2  ; ...
                        2  1  ; ...
                        3  0  ; ...
                        2  1  ; ...
                        3  0  ; ...
                        0  3  ; ...
                        1  2  ; ...
                        3  0  ; ...
                        2  1  ; ...
                        1  2  ; ...
                        0  3  ; ...
                        1  2  ; ...
                        0  3  ; ...
                        3  0  ; ...
                        2  1 ];
LRF_cfg.myTrellis_header.outputs_bin = cell(size(LRF_cfg.myTrellis_header.outputs));
for h=1:size(LRF_cfg.myTrellis_header.outputs,1)
    for hh=1:size(LRF_cfg.myTrellis_header.outputs,2)
        LRF_cfg.myTrellis_header.outputs_bin{h,hh} = de2bi(LRF_cfg.myTrellis_header.outputs(h,hh), 2, 'left-msb');
    end
end

LRF_cfg.myTrellis.numInputSymbols = 2;
LRF_cfg.myTrellis.numOutputSymbols = 8;
LRF_cfg.myTrellis.numStates  = 64;
LRF_cfg.myTrellis.nextStates = [0  1  ; ...
                        2  3  ; ...
                        4  5  ; ...
                        6  7  ; ...
                        8  9  ; ...
                        10  11  ; ...
                        12  13  ; ...
                        14  15  ; ...
                        16  17  ; ...
                        18  19  ; ...
                        20  21  ; ...
                        22  23  ; ...
                        24  25  ; ...
                        26  27  ; ...
                        28  29  ; ...
                        30  31  ; ...
                        32  33  ; ...
                        34  35  ; ...
                        36  37  ; ...
                        38  39  ; ...
                        40  41  ; ...
                        42  43  ; ...
                        44  45  ; ...
                        46  47  ; ...
                        48  49  ; ...
                        50  51  ; ...
                        52  53  ; ...
                        54  55  ; ...
                        56  57  ; ...
                        58  59  ; ...
                        60  61  ; ...
                        62  63  ; ...
                        0  1  ; ...
                        2  3  ; ...
                        4  5  ; ...
                        6  7  ; ...
                        8  9  ; ...
                        10  11  ; ...
                        12  13  ; ...
                        14  15  ; ...
                        16  17  ; ...
                        18  19  ; ...
                        20  21  ; ...
                        22  23  ; ...
                        24  25  ; ...
                        26  27  ; ...
                        28  29  ; ...
                        30  31  ; ...
                        32  33  ; ...
                        34  35  ; ...
                        36  37  ; ...
                        38  39  ; ...
                        40  41  ; ...
                        42  43  ; ...
                        44  45  ; ...
                        46  47  ; ...
                        48  49  ; ...
                        50  51  ; ...
                        52  53  ; ...
                        54  55  ; ...
                        56  57  ; ...
                        58  59  ; ...
                        60  61  ; ...
                        62  63 ];
LRF_cfg.myTrellis.outputs    = [0  7  ; ...
                        3  4  ; ...
                        7  0  ; ...
                        4  3  ; ...
                        6  1  ; ...
                        5  2  ; ...
                        1  6  ; ...
                        2  5  ; ...
                        1  6  ; ...
                        2  5  ; ...
                        6  1  ; ...
                        5  2  ; ...
                        7  0  ; ...
                        4  3  ; ...
                        0  7  ; ...
                        3  4  ; ...
                        4  3  ; ...
                        7  0  ; ...
                        3  4  ; ...
                        0  7  ; ...
                        2  5  ; ...
                        1  6  ; ...
                        5  2  ; ...
                        6  1  ; ...
                        5  2  ; ...
                        6  1  ; ...
                        2  5  ; ...
                        1  6  ; ...
                        3  4  ; ...
                        0  7  ; ...
                        4  3  ; ...
                        7  0  ; ...
                        7  0  ; ...
                        4  3  ; ...
                        0  7  ; ...
                        3  4  ; ...
                        1  6  ; ...
                        2  5  ; ...
                        6  1  ; ...
                        5  2  ; ...
                        6  1  ; ...
                        5  2  ; ...
                        1  6  ; ...
                        2  5  ; ...
                        0  7  ; ...
                        3  4  ; ...
                        7  0  ; ...
                        4  3  ; ...
                        3  4  ; ...
                        0  7  ; ...
                        4  3  ; ...
                        7  0  ; ...
                        5  2  ; ...
                        6  1  ; ...
                        2  5  ; ...
                        1  6  ; ...
                        2  5  ; ...
                        1  6  ; ...
                        5  2  ; ...
                        6  1  ; ...
                        4  3  ; ...
                        7  0  ; ...
                        3  4  ; ...
                        0  7  ];